os: linux
dist: xenial
language: python
python:
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
env:
  global:
  - IMAGE_NAME=nikmang/senti-bot
  - VERSION=0.0.1
  - secure: MxcSLzipZp7rfDdxkRVo/xF1f/a8U3huYnv6hILD5IULwYgHuY9nsQC2b0BxZemlcJhgof2F6JZjNwdR3ZZjUv6HgsPYVIwjS/YkWOLDTaILyXveVvZ3vfp9lFXdLLoJ9xJLHfEc2zw7xjWPDTgF6QbzSVTwffvs91CuebJ3gd7O90gKB9Uy5ECGD1HziyRF1dh0y9UFlrlhCvQs8SDt3ox52hPM30J2hpV5hUlBGeHKyEqNVp1ciTfml2KByg+F+aHvO0ViS/JBXOoZ+qL7hKW7qiiyjCSBDcJfSUTtQZNok4NX6Vm/aU3Y9Y4UvVqwifmYCeehuEHZsNMPzpb1mSR9GUikaCeZDrFq0nPenDkAIae1mroiSgL1J03e4f+wbdEKCvZ703HLInGuIBJjmtrVmwlbtip2vfkqixC/feJn9o5ZaMuJT5ji0Ubi4lZY/fMsqsRYLVXeipU7xex+5Dkma6KOYZluThNDU1OePD59JpObQ8GBAxZN2Vu6NKY5OFdFowD3RNr1cvUr4dbJ0kIF7kvKnyoHknKKO0uP2wmzZWoZ2tKHQWNztH3DhNCx71X4n+k1f0VpxRwUPrv5WYGGrX4mWn2xXFwg6vCwkLZGvAC3Y1q5tm1vt+Chpv8Iisrts7Ot0iOQwFSFObAj8NiratNFEZjepBnLbV0OMr0=
  - secure: f4jrquOAF5knoHluoWpixQKetITb5xQ9qDEIeCiBGABRQ55/rTSNAFKP5ctOl1i2Ma0SqHmAugEhfN3p3c8rnGkO3vu+yhPLwC3wvOvVCeZNzbTTUFHZJgpzinCq6srnyOcjQ7G8WFXgNk1aaNi2pIdgr9ViHv2ZRQnO2NByhVUQ8yfTfQEcA53z5ozw2pATIQFh2emC6BuNoY5T+YgTLR+uQ2EUdThTxBzO1q8CZ+GYk4yKhOHpCMC456+edQgi4gcbv1LIeMEfHeN0pzFTeVrfLkUy7b2zH6UNoy5AjWJJioYai3t0rzTwvWzudz1lBnunPi0oA0b1q1ZUiy7TrYeezp1gGPFOg+MB3ftUOlYI/RKCgkeJZT1IrUJN2NnkDWqVtlgZGQcN86Am5ZShpTzt6xrLwceLSdFXFW4phCViVcg13yFcYF/iW4UmQMvEwJBczkELt0YRZCbdHhRHB0phSC7RUQuudKLuliLB3C4oIrR5LwE6PAF52hDRW1Z1/uRFjolNimbZHSDbkLddRbc/Dx5F5DLe8Nrvya5OqjlBmIpi94mMhViZZ/lu9wJ1R2LGXMMzRTj9ZKxuMlPq+WeWkVS1qi9SI23mmkc+HKAOi/5p/YQpX28QyrAHRgDzo/3iwfAcLw9EYJSpWKbXag8weu35s7ysGq1AGY0r1sc=
matrix:
  fast_finish: true
  allow_failures:
  - python: nightly
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
    - docker build -t $IMAGE_NAME
    - docker push $IMAGE_NAME:$VERSION
    - docker images
install:
- pip install -r requirements.txt
- pip install pytest-cov
script:
- python -m pytest --cov=./ tests/
services:
- docker
after_success:
- codecov
